---
servicename: vnf-manager
environment: production
address: 0.0.0.0
port: 4567
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false

logstash_host: 84.88.40.198
logstash_port: 9999

vnf_catalogue: http://localhost:4569
vnf_provisioning: http://localhost:4572
ns_manager: http://apis.t-nova.eu/orchestrator
gatekeeper: http://192.168.2.19:8000

service_key: 3245cbd3-c8ba-475e-82f2-b0d5edfa7644