---
servicename: hot-generator
environment: production
address: 0.0.0.0
port: 4571
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false

gatekeeper: http://192.168.2.19:8000

service_key: 44646f84-bee6-4ca6-b7e5-047f9004ddaf