---
servicename: vnf-provisioning
environment: production
address: 0.0.0.0
port: 4572
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false

vnf_manager: http://localhost:4568
hot_generator: http://localhost:4571
vim_identity_manager: http://193.136.92.194:5000/v2.0
vim_orchestrator: http://193.136.92.194:8004/v1/db48f31813784568a7d32f8b1ab3a7fc

service_key: 2e98c7b5-18f5-4b12-b704-ed3d3c1ff065