---
servicename: nsd-validator
environment: development
address: 0.0.0.0
port: 4035
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false

ns_catalogue: http://localhost:4012

#monitoring settings:
interval: 0
